tau_weapon_upgrades = {
    "Pulse Rifle": 0,
    "Pulse Carbine": 0,
    "Pulse Pistol": 0,
    "Pulse Blaster": 1,
    "Burst Cannon": 5,
    "Fusion Blaster": 10,
    "Plasma Rifle": 8,
    "Cyclic Ion Blaster": 12,
    "Flamer": 6,
    "Missile Pod": 15,
    "Heavy Burst Cannon": 20,
    "Ion Accelerator": 25,
    "Heavy Rail Rifle": 18,
    "Smart Missile System": 10,
    "High-yield Missile Pod": 15,
    "Railgun": 22,
    "Ion Cannon": 20,
    "Seeker Missiles": 5,
    "Airbursting Fragmentation Projector": 8,
    "Cyclic Ion Raker": 16,
    "Fusion Collider": 18,
}
